language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby
env:
  - DB=postgresql
before_script:
  - git config --global user.name "User Name"
  - git config --global user.email "user@mail.com"
  - psql -c 'create database test' -U postgres
